apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: serviceops
  template:
    metadata:
      labels:
        app: serviceops
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: serviceops-config
            - secretRef:
                name: serviceops-secret
