apiVersion: v1
kind: Secret
metadata:
  name: serviceops-secret
type: Opaque
stringData:
  POSTGRES_DB: serviceops
  POSTGRES_USER: serviceops
  POSTGRES_PASSWORD: serviceops
  SECRET_KEY: supersecret
